variables:
  GIT_STRATEGY: fetch               # we disable fetch, clone or checkout for every job
  GIT_CHECKOUT: "true"              # as we only want to checkout and fetch in the preperation stage
  GIT_SUBMODULE_STRATEGY: recursive    # same as submodules
#  CI_PROJECT_DIR: C:/Users/acub3team/Documents/GitLab-Runner/builds/$CI_COMMIT_REF_SLUG/$CI_PROJECT_NAME

cache:
  key: ${CI_PIPELINE_ID}
  untracked: true
  paths:
    - Binaries/
    - Intermediate/
    - Saved/
    - .vs/
    - Exilium.sln

stages:
  - start
  - preperations
  - build-lightmap
  - compile
  - build
  - cook
  - package
  - cleanup

before_script:
  - echo "Updating scripts ..."
  - pushd %SCRIPTS_DIR%
  - git pull
  - popd

commit-new-release:
  stage: start
  only:
    refs:
      - release
      - schedules
    variables:
      - $SCHEDULED
  cache: {}
  before_script: []
  script:
    - echo "Making a commit to release branch for %CI_PROJECT_NAME% ..."
    - git config --global user.name %GITLAB_USER_NAME%
    - git config --global user.email %GITLAB_USER_EMAIL%
    - git config lfs.http://gitlab-ci-token:%GITLAB_ACCESS_TOKEN%@gitlab.com/TeamACube/Exilium.git/info/lfs.locksverify false
    - git checkout -B master
    - git pull origin master
    - git checkout -B release
    - git merge master
    - git push http://gitlab-ci-token:%GITLAB_ACCESS_TOKEN%@gitlab.com/TeamACube/Exilium.git release

preparations:
  stage: preperations
  script:
    - echo "Preparing %CI_PROJECT_NAME% ..."
    - call "%SCRIPTS_DIR%\PrepareProject.bat"
    - echo "Preparing editor files ..."
    - call "%SCRIPTS_DIR%\PrepareEditor.bat"

.build-lightmap:
  stage: build-lightmap
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build-lightmap/
  script:
    - echo "Rebuilding Lightmaps ..."
    - call "%SCRIPTS_DIR%\PrebuildLightmaps.bat"

.scheduled-build-lightmap:
  stage: build-lightmap
  only:
    - schedules
  script:
    - echo "Rebuilding Lightmaps (Scheduled)..."
    - call "%SCRIPTS_DIR%\PrebuildLightmaps.bat"

compile:
  stage: compile
  script:
    - echo "Compiling Scripts for %CI_PROJECT_NAME% ..."
    - call "%SCRIPTS_DIR%\CompileScripts.bat"

build:
  stage: build
  script:
    - echo "Building %CI_PROJECT_NAME% ..."
    - call "%SCRIPTS_DIR%\BuildProject.bat"

cook:
  stage: cook
  script:
    - echo "Cooking %CI_PROJECT_NAME% ..."
    - call "%SCRIPTS_DIR%\CookProject.bat"

.lightmaps:
  stage: package
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build-lightmap/
  script:
    - echo "Adding lightmaps to the artifacts ..."
    - call "%SCRIPTS_DIR%\ArchiveLightmaps.bat"
  artifacts:
    name: "%CI_PROJECT_NAME%-%CI_COMMIT_REF_NAME%-Lightmaps"
    paths:
      - Artifacts/*-Lightmaps.zip
    expire_in: 7d

.scheduled-lightmaps:
  stage: package
  only:
    - schedules
  script:
    - echo "Adding lightmaps to the artifacts (Scheduled)..."
    - call "%SCRIPTS_DIR%\ArchiveLightmaps.bat"
  artifacts:
    name: "%CI_PROJECT_NAME%-%CI_COMMIT_REF_NAME%-Lightmaps"
    paths:
      - Artifacts/*-Lightmaps.zip
    expire_in: 7d

package:
  stage: package
  only:
    refs:
      - web                 # only archive when started through the web interface
      - schedules           # only archive when started at a specific schedule
    variables:
      - $PACKAGE
  script:
    - echo "Adding build to the artifacts ..."
    - call "%SCRIPTS_DIR%\ArchiveBuild.bat"
  artifacts:
    name: "%CI_PROJECT_NAME%-%CI_COMMIT_REF_NAME%-Build"
    paths:
      - Artifacts/*-Build.zip
    expire_in: 7d

release:
  stage: package
  only:
    - tags                # only archive when a tag is provided
  script:
    - echo "Adding release to the artifacts ..."
    - call "%SCRIPTS_DIR%\ArchiveBuild.bat"
  artifacts:
    name: "%CI_PROJECT_NAME%-%CI_COMMIT_REF_NAME%-Build"
    paths:
      - Artifacts/*-Build.zip
    expire_in: 30d

cleanup:
  stage: cleanup
  when: always
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
    GIT_SUBMODULE_STRATEGY: none
  cache: {}
  before_script: []
  script:
    - echo "Cleaning up ..."
    - echo "%CACHE_PATH%\%CI_PIPELINE_ID%-%CACHE_APPEND%"
    - rmdir /s /q "%CACHE_PATH%\%CI_PIPELINE_ID%-%CACHE_APPEND%"